### ISSUE TITLE
Publish to Azure

### ISSUE THREAD

**Issue by mattjuffs** [mattjuffs/slickcms#14]
Publish to a new Azure Web App. e.g. slickcms.azurewebsites.net

Use continuous deployment from GitHub to Azure.

**Comment by AaronLayton** [comment]
Take a look at https://travis-ci.org/ if Azure doesn't already have a way of doing this ;-)

**Comment by AaronLayton** [comment]
Bitbucket and Gitlab both have Pipelines build in ;-)

**Comment by mattjuffs** [comment]
Azure supports continuous deployment straight from GitHub. 6 of my GitHub repos are deployed to Azure this way.

**Comment by AaronLayton** [comment]
Ha just checked the Continuous Deployment guide - you just pick an Azure config, tell it your Github and then done right.

I wonder if if actually does a deployment of your project? i.e. if files included in the project
or if it just copies your entire repo to the Azure Live site and just runs it from there

**Comment by mattjuffs** [comment]
It looks for the solution/project file(s) and builds it from the repo, prior to deploying.

**Comment by mattjuffs** [comment]
http://slickcms.azurewebsites.net/
