### ISSUE TITLE
SlickCMS.Admin

### ISSUE THREAD

**Issue by mattjuffs** [mattjuffs/slickcms#15]
Create a new Project within the Solution named `SlickCMS.Admin`. Either MVC or Web Forms.

Basic features for the Beta release:

- [x] Login
- [x] View Posts
- [x] Add Post
- [x] Edit Post
- [x] Save Categories & Tags

**Comment by AaronLayton** [comment]
- [ ] Login
- [ ] View Posts
- [ ] Add/Edit Post
- [ ] Manage Categories
- [ ] Manage Tags
- [ ] Manage Settings
- [x] Show @mattjuffs how to Github

Also you're probably more used to a Trello workflow? https://github.com/mattjuffs/slickcms/projects

**Comment by mattjuffs** [comment]
Yeah probably, will try the Projects soon. I've copied these issues over from a Trello board anyway.

**Comment by AaronLayton** [comment]
Nice ;-)
