### ISSUE TITLE
WER DA CODE

### ISSUE THREAD

**Issue by mikeres0** [mattjuffs/slickcms#2]
OI M8 WER DA CODE

**Comment by AaronLayton** [comment]
I second that - I don't there there is a CMS

or that it's so slick that it's slide right out of the repo

**Comment by mikeres0** [comment]
What is a CMS?

**Comment by AaronLayton** [comment]
what is a Slick?

**Comment by mattjuffs** [comment]
You're a Slick.

**Comment by AaronLayton** [comment]
Slick

**Comment by mikeres0** [comment]
plz release code 4 muy

**Comment by mattjuffs** [comment]
I've merged your pull request.

**Comment by mikeres0** [comment]
@mattjuffs thanks, +1 for taking 6 days to merge 👎

**Comment by AaronLayton** [comment]
Does that mean you can close this issue now @mattjuffs ?

**Comment by mikeres0** [comment]
@AaronLayton I will close the issue so it doesn't take 6 days
